// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc_profile_service.proto

// Protobuf Java Version: 3.25.5
package com.lreas.grpc;

public final class GrpcProfileServiceOuterClass {
  private GrpcProfileServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetUserInfoGrpcOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.lreas.grpc.GetUserInfoGrpc)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string userId = 1;</code>
     * @return The userId.
     */
    java.lang.String getUserId();
    /**
     * <code>string userId = 1;</code>
     * @return The bytes for userId.
     */
    com.google.protobuf.ByteString
        getUserIdBytes();
  }
  /**
   * Protobuf type {@code com.lreas.grpc.GetUserInfoGrpc}
   */
  public static final class GetUserInfoGrpc extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.lreas.grpc.GetUserInfoGrpc)
      GetUserInfoGrpcOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetUserInfoGrpc.newBuilder() to construct.
    private GetUserInfoGrpc(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetUserInfoGrpc() {
      userId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetUserInfoGrpc();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lreas.grpc.GrpcProfileServiceOuterClass.internal_static_com_lreas_grpc_GetUserInfoGrpc_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lreas.grpc.GrpcProfileServiceOuterClass.internal_static_com_lreas_grpc_GetUserInfoGrpc_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lreas.grpc.GrpcProfileServiceOuterClass.GetUserInfoGrpc.class, com.lreas.grpc.GrpcProfileServiceOuterClass.GetUserInfoGrpc.Builder.class);
    }

    public static final int USERID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object userId_ = "";
    /**
     * <code>string userId = 1;</code>
     * @return The userId.
     */
    @java.lang.Override
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <code>string userId = 1;</code>
     * @return The bytes for userId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.lreas.grpc.GrpcProfileServiceOuterClass.GetUserInfoGrpc)) {
        return super.equals(obj);
      }
      com.lreas.grpc.GrpcProfileServiceOuterClass.GetUserInfoGrpc other = (com.lreas.grpc.GrpcProfileServiceOuterClass.GetUserInfoGrpc) obj;

      if (!getUserId()
          .equals(other.getUserId())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.lreas.grpc.GrpcProfileServiceOuterClass.GetUserInfoGrpc parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lreas.grpc.GrpcProfileServiceOuterClass.GetUserInfoGrpc parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lreas.grpc.GrpcProfileServiceOuterClass.GetUserInfoGrpc parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lreas.grpc.GrpcProfileServiceOuterClass.GetUserInfoGrpc parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lreas.grpc.GrpcProfileServiceOuterClass.GetUserInfoGrpc parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lreas.grpc.GrpcProfileServiceOuterClass.GetUserInfoGrpc parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lreas.grpc.GrpcProfileServiceOuterClass.GetUserInfoGrpc parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lreas.grpc.GrpcProfileServiceOuterClass.GetUserInfoGrpc parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.lreas.grpc.GrpcProfileServiceOuterClass.GetUserInfoGrpc parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.lreas.grpc.GrpcProfileServiceOuterClass.GetUserInfoGrpc parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lreas.grpc.GrpcProfileServiceOuterClass.GetUserInfoGrpc parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lreas.grpc.GrpcProfileServiceOuterClass.GetUserInfoGrpc parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.lreas.grpc.GrpcProfileServiceOuterClass.GetUserInfoGrpc prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.lreas.grpc.GetUserInfoGrpc}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.lreas.grpc.GetUserInfoGrpc)
        com.lreas.grpc.GrpcProfileServiceOuterClass.GetUserInfoGrpcOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lreas.grpc.GrpcProfileServiceOuterClass.internal_static_com_lreas_grpc_GetUserInfoGrpc_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lreas.grpc.GrpcProfileServiceOuterClass.internal_static_com_lreas_grpc_GetUserInfoGrpc_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lreas.grpc.GrpcProfileServiceOuterClass.GetUserInfoGrpc.class, com.lreas.grpc.GrpcProfileServiceOuterClass.GetUserInfoGrpc.Builder.class);
      }

      // Construct using com.lreas.grpc.GrpcProfileServiceOuterClass.GetUserInfoGrpc.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        userId_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lreas.grpc.GrpcProfileServiceOuterClass.internal_static_com_lreas_grpc_GetUserInfoGrpc_descriptor;
      }

      @java.lang.Override
      public com.lreas.grpc.GrpcProfileServiceOuterClass.GetUserInfoGrpc getDefaultInstanceForType() {
        return com.lreas.grpc.GrpcProfileServiceOuterClass.GetUserInfoGrpc.getDefaultInstance();
      }

      @java.lang.Override
      public com.lreas.grpc.GrpcProfileServiceOuterClass.GetUserInfoGrpc build() {
        com.lreas.grpc.GrpcProfileServiceOuterClass.GetUserInfoGrpc result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.lreas.grpc.GrpcProfileServiceOuterClass.GetUserInfoGrpc buildPartial() {
        com.lreas.grpc.GrpcProfileServiceOuterClass.GetUserInfoGrpc result = new com.lreas.grpc.GrpcProfileServiceOuterClass.GetUserInfoGrpc(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.lreas.grpc.GrpcProfileServiceOuterClass.GetUserInfoGrpc result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.userId_ = userId_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lreas.grpc.GrpcProfileServiceOuterClass.GetUserInfoGrpc) {
          return mergeFrom((com.lreas.grpc.GrpcProfileServiceOuterClass.GetUserInfoGrpc)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lreas.grpc.GrpcProfileServiceOuterClass.GetUserInfoGrpc other) {
        if (other == com.lreas.grpc.GrpcProfileServiceOuterClass.GetUserInfoGrpc.getDefaultInstance()) return this;
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                userId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object userId_ = "";
      /**
       * <code>string userId = 1;</code>
       * @return The userId.
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string userId = 1;</code>
       * @return The bytes for userId.
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string userId = 1;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        userId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string userId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        userId_ = getDefaultInstance().getUserId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string userId = 1;</code>
       * @param value The bytes for userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        userId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.lreas.grpc.GetUserInfoGrpc)
    }

    // @@protoc_insertion_point(class_scope:com.lreas.grpc.GetUserInfoGrpc)
    private static final com.lreas.grpc.GrpcProfileServiceOuterClass.GetUserInfoGrpc DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.lreas.grpc.GrpcProfileServiceOuterClass.GetUserInfoGrpc();
    }

    public static com.lreas.grpc.GrpcProfileServiceOuterClass.GetUserInfoGrpc getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetUserInfoGrpc>
        PARSER = new com.google.protobuf.AbstractParser<GetUserInfoGrpc>() {
      @java.lang.Override
      public GetUserInfoGrpc parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GetUserInfoGrpc> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetUserInfoGrpc> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.lreas.grpc.GrpcProfileServiceOuterClass.GetUserInfoGrpc getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UserInfoGrpcOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.lreas.grpc.UserInfoGrpc)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string avtPath = 1;</code>
     * @return The avtPath.
     */
    java.lang.String getAvtPath();
    /**
     * <code>string avtPath = 1;</code>
     * @return The bytes for avtPath.
     */
    com.google.protobuf.ByteString
        getAvtPathBytes();

    /**
     * <code>string userName = 2;</code>
     * @return The userName.
     */
    java.lang.String getUserName();
    /**
     * <code>string userName = 2;</code>
     * @return The bytes for userName.
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    /**
     * <code>string birthday = 3;</code>
     * @return The birthday.
     */
    java.lang.String getBirthday();
    /**
     * <code>string birthday = 3;</code>
     * @return The bytes for birthday.
     */
    com.google.protobuf.ByteString
        getBirthdayBytes();

    /**
     * <code>string gender = 4;</code>
     * @return The gender.
     */
    java.lang.String getGender();
    /**
     * <code>string gender = 4;</code>
     * @return The bytes for gender.
     */
    com.google.protobuf.ByteString
        getGenderBytes();

    /**
     * <code>string otherGender = 5;</code>
     * @return The otherGender.
     */
    java.lang.String getOtherGender();
    /**
     * <code>string otherGender = 5;</code>
     * @return The bytes for otherGender.
     */
    com.google.protobuf.ByteString
        getOtherGenderBytes();

    /**
     * <code>string description = 6;</code>
     * @return The description.
     */
    java.lang.String getDescription();
    /**
     * <code>string description = 6;</code>
     * @return The bytes for description.
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>string email = 7;</code>
     * @return The email.
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 7;</code>
     * @return The bytes for email.
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>string phone = 8;</code>
     * @return The phone.
     */
    java.lang.String getPhone();
    /**
     * <code>string phone = 8;</code>
     * @return The bytes for phone.
     */
    com.google.protobuf.ByteString
        getPhoneBytes();

    /**
     * <code>string address = 9;</code>
     * @return The address.
     */
    java.lang.String getAddress();
    /**
     * <code>string address = 9;</code>
     * @return The bytes for address.
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    /**
     * <code>string institutionName = 10;</code>
     * @return The institutionName.
     */
    java.lang.String getInstitutionName();
    /**
     * <code>string institutionName = 10;</code>
     * @return The bytes for institutionName.
     */
    com.google.protobuf.ByteString
        getInstitutionNameBytes();

    /**
     * <code>string invitationCode = 11;</code>
     * @return The invitationCode.
     */
    java.lang.String getInvitationCode();
    /**
     * <code>string invitationCode = 11;</code>
     * @return The bytes for invitationCode.
     */
    com.google.protobuf.ByteString
        getInvitationCodeBytes();
  }
  /**
   * Protobuf type {@code com.lreas.grpc.UserInfoGrpc}
   */
  public static final class UserInfoGrpc extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.lreas.grpc.UserInfoGrpc)
      UserInfoGrpcOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserInfoGrpc.newBuilder() to construct.
    private UserInfoGrpc(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserInfoGrpc() {
      avtPath_ = "";
      userName_ = "";
      birthday_ = "";
      gender_ = "";
      otherGender_ = "";
      description_ = "";
      email_ = "";
      phone_ = "";
      address_ = "";
      institutionName_ = "";
      invitationCode_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UserInfoGrpc();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lreas.grpc.GrpcProfileServiceOuterClass.internal_static_com_lreas_grpc_UserInfoGrpc_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lreas.grpc.GrpcProfileServiceOuterClass.internal_static_com_lreas_grpc_UserInfoGrpc_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lreas.grpc.GrpcProfileServiceOuterClass.UserInfoGrpc.class, com.lreas.grpc.GrpcProfileServiceOuterClass.UserInfoGrpc.Builder.class);
    }

    public static final int AVTPATH_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object avtPath_ = "";
    /**
     * <code>string avtPath = 1;</code>
     * @return The avtPath.
     */
    @java.lang.Override
    public java.lang.String getAvtPath() {
      java.lang.Object ref = avtPath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        avtPath_ = s;
        return s;
      }
    }
    /**
     * <code>string avtPath = 1;</code>
     * @return The bytes for avtPath.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAvtPathBytes() {
      java.lang.Object ref = avtPath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        avtPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERNAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object userName_ = "";
    /**
     * <code>string userName = 2;</code>
     * @return The userName.
     */
    @java.lang.Override
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      }
    }
    /**
     * <code>string userName = 2;</code>
     * @return The bytes for userName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BIRTHDAY_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object birthday_ = "";
    /**
     * <code>string birthday = 3;</code>
     * @return The birthday.
     */
    @java.lang.Override
    public java.lang.String getBirthday() {
      java.lang.Object ref = birthday_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        birthday_ = s;
        return s;
      }
    }
    /**
     * <code>string birthday = 3;</code>
     * @return The bytes for birthday.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBirthdayBytes() {
      java.lang.Object ref = birthday_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        birthday_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GENDER_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object gender_ = "";
    /**
     * <code>string gender = 4;</code>
     * @return The gender.
     */
    @java.lang.Override
    public java.lang.String getGender() {
      java.lang.Object ref = gender_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gender_ = s;
        return s;
      }
    }
    /**
     * <code>string gender = 4;</code>
     * @return The bytes for gender.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGenderBytes() {
      java.lang.Object ref = gender_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OTHERGENDER_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object otherGender_ = "";
    /**
     * <code>string otherGender = 5;</code>
     * @return The otherGender.
     */
    @java.lang.Override
    public java.lang.String getOtherGender() {
      java.lang.Object ref = otherGender_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        otherGender_ = s;
        return s;
      }
    }
    /**
     * <code>string otherGender = 5;</code>
     * @return The bytes for otherGender.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOtherGenderBytes() {
      java.lang.Object ref = otherGender_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        otherGender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object description_ = "";
    /**
     * <code>string description = 6;</code>
     * @return The description.
     */
    @java.lang.Override
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>string description = 6;</code>
     * @return The bytes for description.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private volatile java.lang.Object email_ = "";
    /**
     * <code>string email = 7;</code>
     * @return The email.
     */
    @java.lang.Override
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 7;</code>
     * @return The bytes for email.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHONE_FIELD_NUMBER = 8;
    @SuppressWarnings("serial")
    private volatile java.lang.Object phone_ = "";
    /**
     * <code>string phone = 8;</code>
     * @return The phone.
     */
    @java.lang.Override
    public java.lang.String getPhone() {
      java.lang.Object ref = phone_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        phone_ = s;
        return s;
      }
    }
    /**
     * <code>string phone = 8;</code>
     * @return The bytes for phone.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPhoneBytes() {
      java.lang.Object ref = phone_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADDRESS_FIELD_NUMBER = 9;
    @SuppressWarnings("serial")
    private volatile java.lang.Object address_ = "";
    /**
     * <code>string address = 9;</code>
     * @return The address.
     */
    @java.lang.Override
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <code>string address = 9;</code>
     * @return The bytes for address.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INSTITUTIONNAME_FIELD_NUMBER = 10;
    @SuppressWarnings("serial")
    private volatile java.lang.Object institutionName_ = "";
    /**
     * <code>string institutionName = 10;</code>
     * @return The institutionName.
     */
    @java.lang.Override
    public java.lang.String getInstitutionName() {
      java.lang.Object ref = institutionName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        institutionName_ = s;
        return s;
      }
    }
    /**
     * <code>string institutionName = 10;</code>
     * @return The bytes for institutionName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getInstitutionNameBytes() {
      java.lang.Object ref = institutionName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        institutionName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INVITATIONCODE_FIELD_NUMBER = 11;
    @SuppressWarnings("serial")
    private volatile java.lang.Object invitationCode_ = "";
    /**
     * <code>string invitationCode = 11;</code>
     * @return The invitationCode.
     */
    @java.lang.Override
    public java.lang.String getInvitationCode() {
      java.lang.Object ref = invitationCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        invitationCode_ = s;
        return s;
      }
    }
    /**
     * <code>string invitationCode = 11;</code>
     * @return The bytes for invitationCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getInvitationCodeBytes() {
      java.lang.Object ref = invitationCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        invitationCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(avtPath_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, avtPath_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(birthday_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, birthday_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(gender_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, gender_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(otherGender_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, otherGender_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, description_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, email_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(phone_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, phone_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(address_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, address_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(institutionName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, institutionName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(invitationCode_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, invitationCode_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(avtPath_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, avtPath_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(birthday_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, birthday_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(gender_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, gender_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(otherGender_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, otherGender_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, description_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, email_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(phone_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, phone_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(address_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, address_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(institutionName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, institutionName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(invitationCode_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, invitationCode_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.lreas.grpc.GrpcProfileServiceOuterClass.UserInfoGrpc)) {
        return super.equals(obj);
      }
      com.lreas.grpc.GrpcProfileServiceOuterClass.UserInfoGrpc other = (com.lreas.grpc.GrpcProfileServiceOuterClass.UserInfoGrpc) obj;

      if (!getAvtPath()
          .equals(other.getAvtPath())) return false;
      if (!getUserName()
          .equals(other.getUserName())) return false;
      if (!getBirthday()
          .equals(other.getBirthday())) return false;
      if (!getGender()
          .equals(other.getGender())) return false;
      if (!getOtherGender()
          .equals(other.getOtherGender())) return false;
      if (!getDescription()
          .equals(other.getDescription())) return false;
      if (!getEmail()
          .equals(other.getEmail())) return false;
      if (!getPhone()
          .equals(other.getPhone())) return false;
      if (!getAddress()
          .equals(other.getAddress())) return false;
      if (!getInstitutionName()
          .equals(other.getInstitutionName())) return false;
      if (!getInvitationCode()
          .equals(other.getInvitationCode())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + AVTPATH_FIELD_NUMBER;
      hash = (53 * hash) + getAvtPath().hashCode();
      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUserName().hashCode();
      hash = (37 * hash) + BIRTHDAY_FIELD_NUMBER;
      hash = (53 * hash) + getBirthday().hashCode();
      hash = (37 * hash) + GENDER_FIELD_NUMBER;
      hash = (53 * hash) + getGender().hashCode();
      hash = (37 * hash) + OTHERGENDER_FIELD_NUMBER;
      hash = (53 * hash) + getOtherGender().hashCode();
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      hash = (37 * hash) + PHONE_FIELD_NUMBER;
      hash = (53 * hash) + getPhone().hashCode();
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (37 * hash) + INSTITUTIONNAME_FIELD_NUMBER;
      hash = (53 * hash) + getInstitutionName().hashCode();
      hash = (37 * hash) + INVITATIONCODE_FIELD_NUMBER;
      hash = (53 * hash) + getInvitationCode().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.lreas.grpc.GrpcProfileServiceOuterClass.UserInfoGrpc parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lreas.grpc.GrpcProfileServiceOuterClass.UserInfoGrpc parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lreas.grpc.GrpcProfileServiceOuterClass.UserInfoGrpc parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lreas.grpc.GrpcProfileServiceOuterClass.UserInfoGrpc parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lreas.grpc.GrpcProfileServiceOuterClass.UserInfoGrpc parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lreas.grpc.GrpcProfileServiceOuterClass.UserInfoGrpc parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lreas.grpc.GrpcProfileServiceOuterClass.UserInfoGrpc parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lreas.grpc.GrpcProfileServiceOuterClass.UserInfoGrpc parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.lreas.grpc.GrpcProfileServiceOuterClass.UserInfoGrpc parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.lreas.grpc.GrpcProfileServiceOuterClass.UserInfoGrpc parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lreas.grpc.GrpcProfileServiceOuterClass.UserInfoGrpc parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lreas.grpc.GrpcProfileServiceOuterClass.UserInfoGrpc parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.lreas.grpc.GrpcProfileServiceOuterClass.UserInfoGrpc prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.lreas.grpc.UserInfoGrpc}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.lreas.grpc.UserInfoGrpc)
        com.lreas.grpc.GrpcProfileServiceOuterClass.UserInfoGrpcOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lreas.grpc.GrpcProfileServiceOuterClass.internal_static_com_lreas_grpc_UserInfoGrpc_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lreas.grpc.GrpcProfileServiceOuterClass.internal_static_com_lreas_grpc_UserInfoGrpc_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lreas.grpc.GrpcProfileServiceOuterClass.UserInfoGrpc.class, com.lreas.grpc.GrpcProfileServiceOuterClass.UserInfoGrpc.Builder.class);
      }

      // Construct using com.lreas.grpc.GrpcProfileServiceOuterClass.UserInfoGrpc.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        avtPath_ = "";
        userName_ = "";
        birthday_ = "";
        gender_ = "";
        otherGender_ = "";
        description_ = "";
        email_ = "";
        phone_ = "";
        address_ = "";
        institutionName_ = "";
        invitationCode_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lreas.grpc.GrpcProfileServiceOuterClass.internal_static_com_lreas_grpc_UserInfoGrpc_descriptor;
      }

      @java.lang.Override
      public com.lreas.grpc.GrpcProfileServiceOuterClass.UserInfoGrpc getDefaultInstanceForType() {
        return com.lreas.grpc.GrpcProfileServiceOuterClass.UserInfoGrpc.getDefaultInstance();
      }

      @java.lang.Override
      public com.lreas.grpc.GrpcProfileServiceOuterClass.UserInfoGrpc build() {
        com.lreas.grpc.GrpcProfileServiceOuterClass.UserInfoGrpc result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.lreas.grpc.GrpcProfileServiceOuterClass.UserInfoGrpc buildPartial() {
        com.lreas.grpc.GrpcProfileServiceOuterClass.UserInfoGrpc result = new com.lreas.grpc.GrpcProfileServiceOuterClass.UserInfoGrpc(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.lreas.grpc.GrpcProfileServiceOuterClass.UserInfoGrpc result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.avtPath_ = avtPath_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.userName_ = userName_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.birthday_ = birthday_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.gender_ = gender_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.otherGender_ = otherGender_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.description_ = description_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.email_ = email_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.phone_ = phone_;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.address_ = address_;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.institutionName_ = institutionName_;
        }
        if (((from_bitField0_ & 0x00000400) != 0)) {
          result.invitationCode_ = invitationCode_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lreas.grpc.GrpcProfileServiceOuterClass.UserInfoGrpc) {
          return mergeFrom((com.lreas.grpc.GrpcProfileServiceOuterClass.UserInfoGrpc)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lreas.grpc.GrpcProfileServiceOuterClass.UserInfoGrpc other) {
        if (other == com.lreas.grpc.GrpcProfileServiceOuterClass.UserInfoGrpc.getDefaultInstance()) return this;
        if (!other.getAvtPath().isEmpty()) {
          avtPath_ = other.avtPath_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getUserName().isEmpty()) {
          userName_ = other.userName_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getBirthday().isEmpty()) {
          birthday_ = other.birthday_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getGender().isEmpty()) {
          gender_ = other.gender_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.getOtherGender().isEmpty()) {
          otherGender_ = other.otherGender_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          bitField0_ |= 0x00000040;
          onChanged();
        }
        if (!other.getPhone().isEmpty()) {
          phone_ = other.phone_;
          bitField0_ |= 0x00000080;
          onChanged();
        }
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          bitField0_ |= 0x00000100;
          onChanged();
        }
        if (!other.getInstitutionName().isEmpty()) {
          institutionName_ = other.institutionName_;
          bitField0_ |= 0x00000200;
          onChanged();
        }
        if (!other.getInvitationCode().isEmpty()) {
          invitationCode_ = other.invitationCode_;
          bitField0_ |= 0x00000400;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                avtPath_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                userName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                birthday_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                gender_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                otherGender_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                description_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 58: {
                email_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              case 66: {
                phone_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000080;
                break;
              } // case 66
              case 74: {
                address_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000100;
                break;
              } // case 74
              case 82: {
                institutionName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000200;
                break;
              } // case 82
              case 90: {
                invitationCode_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000400;
                break;
              } // case 90
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object avtPath_ = "";
      /**
       * <code>string avtPath = 1;</code>
       * @return The avtPath.
       */
      public java.lang.String getAvtPath() {
        java.lang.Object ref = avtPath_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          avtPath_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string avtPath = 1;</code>
       * @return The bytes for avtPath.
       */
      public com.google.protobuf.ByteString
          getAvtPathBytes() {
        java.lang.Object ref = avtPath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          avtPath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string avtPath = 1;</code>
       * @param value The avtPath to set.
       * @return This builder for chaining.
       */
      public Builder setAvtPath(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        avtPath_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string avtPath = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAvtPath() {
        avtPath_ = getDefaultInstance().getAvtPath();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string avtPath = 1;</code>
       * @param value The bytes for avtPath to set.
       * @return This builder for chaining.
       */
      public Builder setAvtPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        avtPath_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object userName_ = "";
      /**
       * <code>string userName = 2;</code>
       * @return The userName.
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string userName = 2;</code>
       * @return The bytes for userName.
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string userName = 2;</code>
       * @param value The userName to set.
       * @return This builder for chaining.
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        userName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string userName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserName() {
        userName_ = getDefaultInstance().getUserName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string userName = 2;</code>
       * @param value The bytes for userName to set.
       * @return This builder for chaining.
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        userName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object birthday_ = "";
      /**
       * <code>string birthday = 3;</code>
       * @return The birthday.
       */
      public java.lang.String getBirthday() {
        java.lang.Object ref = birthday_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          birthday_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string birthday = 3;</code>
       * @return The bytes for birthday.
       */
      public com.google.protobuf.ByteString
          getBirthdayBytes() {
        java.lang.Object ref = birthday_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          birthday_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string birthday = 3;</code>
       * @param value The birthday to set.
       * @return This builder for chaining.
       */
      public Builder setBirthday(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        birthday_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string birthday = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearBirthday() {
        birthday_ = getDefaultInstance().getBirthday();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string birthday = 3;</code>
       * @param value The bytes for birthday to set.
       * @return This builder for chaining.
       */
      public Builder setBirthdayBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        birthday_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object gender_ = "";
      /**
       * <code>string gender = 4;</code>
       * @return The gender.
       */
      public java.lang.String getGender() {
        java.lang.Object ref = gender_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          gender_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string gender = 4;</code>
       * @return The bytes for gender.
       */
      public com.google.protobuf.ByteString
          getGenderBytes() {
        java.lang.Object ref = gender_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gender_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string gender = 4;</code>
       * @param value The gender to set.
       * @return This builder for chaining.
       */
      public Builder setGender(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        gender_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string gender = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearGender() {
        gender_ = getDefaultInstance().getGender();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string gender = 4;</code>
       * @param value The bytes for gender to set.
       * @return This builder for chaining.
       */
      public Builder setGenderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        gender_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object otherGender_ = "";
      /**
       * <code>string otherGender = 5;</code>
       * @return The otherGender.
       */
      public java.lang.String getOtherGender() {
        java.lang.Object ref = otherGender_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          otherGender_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string otherGender = 5;</code>
       * @return The bytes for otherGender.
       */
      public com.google.protobuf.ByteString
          getOtherGenderBytes() {
        java.lang.Object ref = otherGender_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          otherGender_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string otherGender = 5;</code>
       * @param value The otherGender to set.
       * @return This builder for chaining.
       */
      public Builder setOtherGender(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        otherGender_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string otherGender = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearOtherGender() {
        otherGender_ = getDefaultInstance().getOtherGender();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string otherGender = 5;</code>
       * @param value The bytes for otherGender to set.
       * @return This builder for chaining.
       */
      public Builder setOtherGenderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        otherGender_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>string description = 6;</code>
       * @return The description.
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string description = 6;</code>
       * @return The bytes for description.
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description = 6;</code>
       * @param value The description to set.
       * @return This builder for chaining.
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        description_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>string description = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearDescription() {
        description_ = getDefaultInstance().getDescription();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>string description = 6;</code>
       * @param value The bytes for description to set.
       * @return This builder for chaining.
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        description_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>string email = 7;</code>
       * @return The email.
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string email = 7;</code>
       * @return The bytes for email.
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 7;</code>
       * @param value The email to set.
       * @return This builder for chaining.
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        email_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmail() {
        email_ = getDefaultInstance().getEmail();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <code>string email = 7;</code>
       * @param value The bytes for email to set.
       * @return This builder for chaining.
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        email_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }

      private java.lang.Object phone_ = "";
      /**
       * <code>string phone = 8;</code>
       * @return The phone.
       */
      public java.lang.String getPhone() {
        java.lang.Object ref = phone_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          phone_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string phone = 8;</code>
       * @return The bytes for phone.
       */
      public com.google.protobuf.ByteString
          getPhoneBytes() {
        java.lang.Object ref = phone_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          phone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string phone = 8;</code>
       * @param value The phone to set.
       * @return This builder for chaining.
       */
      public Builder setPhone(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        phone_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>string phone = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearPhone() {
        phone_ = getDefaultInstance().getPhone();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      /**
       * <code>string phone = 8;</code>
       * @param value The bytes for phone to set.
       * @return This builder for chaining.
       */
      public Builder setPhoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        phone_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }

      private java.lang.Object address_ = "";
      /**
       * <code>string address = 9;</code>
       * @return The address.
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string address = 9;</code>
       * @return The bytes for address.
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string address = 9;</code>
       * @param value The address to set.
       * @return This builder for chaining.
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        address_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>string address = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearAddress() {
        address_ = getDefaultInstance().getAddress();
        bitField0_ = (bitField0_ & ~0x00000100);
        onChanged();
        return this;
      }
      /**
       * <code>string address = 9;</code>
       * @param value The bytes for address to set.
       * @return This builder for chaining.
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        address_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }

      private java.lang.Object institutionName_ = "";
      /**
       * <code>string institutionName = 10;</code>
       * @return The institutionName.
       */
      public java.lang.String getInstitutionName() {
        java.lang.Object ref = institutionName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          institutionName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string institutionName = 10;</code>
       * @return The bytes for institutionName.
       */
      public com.google.protobuf.ByteString
          getInstitutionNameBytes() {
        java.lang.Object ref = institutionName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          institutionName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string institutionName = 10;</code>
       * @param value The institutionName to set.
       * @return This builder for chaining.
       */
      public Builder setInstitutionName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        institutionName_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <code>string institutionName = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearInstitutionName() {
        institutionName_ = getDefaultInstance().getInstitutionName();
        bitField0_ = (bitField0_ & ~0x00000200);
        onChanged();
        return this;
      }
      /**
       * <code>string institutionName = 10;</code>
       * @param value The bytes for institutionName to set.
       * @return This builder for chaining.
       */
      public Builder setInstitutionNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        institutionName_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }

      private java.lang.Object invitationCode_ = "";
      /**
       * <code>string invitationCode = 11;</code>
       * @return The invitationCode.
       */
      public java.lang.String getInvitationCode() {
        java.lang.Object ref = invitationCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          invitationCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string invitationCode = 11;</code>
       * @return The bytes for invitationCode.
       */
      public com.google.protobuf.ByteString
          getInvitationCodeBytes() {
        java.lang.Object ref = invitationCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          invitationCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string invitationCode = 11;</code>
       * @param value The invitationCode to set.
       * @return This builder for chaining.
       */
      public Builder setInvitationCode(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        invitationCode_ = value;
        bitField0_ |= 0x00000400;
        onChanged();
        return this;
      }
      /**
       * <code>string invitationCode = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearInvitationCode() {
        invitationCode_ = getDefaultInstance().getInvitationCode();
        bitField0_ = (bitField0_ & ~0x00000400);
        onChanged();
        return this;
      }
      /**
       * <code>string invitationCode = 11;</code>
       * @param value The bytes for invitationCode to set.
       * @return This builder for chaining.
       */
      public Builder setInvitationCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        invitationCode_ = value;
        bitField0_ |= 0x00000400;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.lreas.grpc.UserInfoGrpc)
    }

    // @@protoc_insertion_point(class_scope:com.lreas.grpc.UserInfoGrpc)
    private static final com.lreas.grpc.GrpcProfileServiceOuterClass.UserInfoGrpc DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.lreas.grpc.GrpcProfileServiceOuterClass.UserInfoGrpc();
    }

    public static com.lreas.grpc.GrpcProfileServiceOuterClass.UserInfoGrpc getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserInfoGrpc>
        PARSER = new com.google.protobuf.AbstractParser<UserInfoGrpc>() {
      @java.lang.Override
      public UserInfoGrpc parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<UserInfoGrpc> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserInfoGrpc> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.lreas.grpc.GrpcProfileServiceOuterClass.UserInfoGrpc getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lreas_grpc_GetUserInfoGrpc_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lreas_grpc_GetUserInfoGrpc_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lreas_grpc_UserInfoGrpc_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lreas_grpc_UserInfoGrpc_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032grpc_profile_service.proto\022\016com.lreas." +
      "grpc\"!\n\017GetUserInfoGrpc\022\016\n\006userId\030\001 \001(\t\"" +
      "\335\001\n\014UserInfoGrpc\022\017\n\007avtPath\030\001 \001(\t\022\020\n\010use" +
      "rName\030\002 \001(\t\022\020\n\010birthday\030\003 \001(\t\022\016\n\006gender\030" +
      "\004 \001(\t\022\023\n\013otherGender\030\005 \001(\t\022\023\n\013descriptio" +
      "n\030\006 \001(\t\022\r\n\005email\030\007 \001(\t\022\r\n\005phone\030\010 \001(\t\022\017\n" +
      "\007address\030\t \001(\t\022\027\n\017institutionName\030\n \001(\t\022" +
      "\026\n\016invitationCode\030\013 \001(\t2b\n\022GrpcProfileSe" +
      "rvice\022L\n\013getUserInfo\022\037.com.lreas.grpc.Ge" +
      "tUserInfoGrpc\032\034.com.lreas.grpc.UserInfoG" +
      "rpcb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_lreas_grpc_GetUserInfoGrpc_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_lreas_grpc_GetUserInfoGrpc_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lreas_grpc_GetUserInfoGrpc_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_com_lreas_grpc_UserInfoGrpc_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_lreas_grpc_UserInfoGrpc_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lreas_grpc_UserInfoGrpc_descriptor,
        new java.lang.String[] { "AvtPath", "UserName", "Birthday", "Gender", "OtherGender", "Description", "Email", "Phone", "Address", "InstitutionName", "InvitationCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
