package com.lreas.file_management.models;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import java.time.Instant;

@Document(collection = "documents")
public class DocumentEntity {
    @Id
    private String id;  // Automatically generated by MongoDB
    private String content;
    private Instant updatedAt;

    // Default constructor (required by Spring Data)
    public DocumentEntity() {}

    // Constructor to initialize content and timestamp
    public DocumentEntity(String content) {
        this.content = content;
        this.updatedAt = Instant.now();
    }

    // Getters
    public String getId() { return id; }
    public String getContent() { return content; }
    public Instant getUpdatedAt() { return updatedAt; }

    // Setters (no setter for id, as it's auto-generated)
    public void setContent(String content) { this.content = content; }
    public void setUpdatedAt(Instant updatedAt) { this.updatedAt = updatedAt; }
}
